// <auto-generated />
using Mango.CouponApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.CouponApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221230062810_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("Mango.CouponApi.Models.Coupon", b =>
                {
                    b.Property<string>("CouponCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("REAL");

                    b.HasKey("CouponCode");

                    b.ToTable("Coupons");
                });
#pragma warning restore 612, 618
        }
    }
}
